name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-release:
        permissions:
            contents: write
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "22"

            - name: Enable Corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build
              run: yarn build

            - name: Package executable
              run: yarn package:win

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: releases/windows/goblin-malin-win-x64.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
